project:
  type: website
  output-dir: docs

website:
  title: "Deserción estudiantil"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: data_cleaning.qmd
        text: Limpieza
      - href: visualizations.qmd
        text: Visualizaciones

format:
  html:
    theme: cosmo